create modal photos
riimako/portfolio pull request #13
Opened 2020-10-19 14:52 UTC by JenniferGoijman

2020-10-19 15:08 UTC, riimako requested changes

2020-10-19 15:08 UTC, riimako commented on src/components/ModalPhotos/ModalPhotos.tsx
> +  const images: Array<any> = [
para facilitar la vida luego. 
creas una interfaz IImage y el array<any> lo sustituyes por array de IImage?

gracias

2020-10-20 13:55 UTC, JenniferGoijman commented on src/components/ModalPhotos/ModalPhotos.tsx
> +  const images: Array<any> = [
listo, doña 👍

2020-10-20 14:02 UTC, riimako requested changes

2020-10-20 14:02 UTC, riimako commented on src/images.tsx
> +export const images: Array<any> = [
Sigue siendo any, quiero ese any a un interfaz:
IImage = {id: number, image:string}

2020-10-20 15:18 UTC, JenniferGoijman commented on src/images.tsx
> +export const images: Array<any> = [
ahora si, eso espero

2020-10-21 09:35 UTC, riimako approved these changes

2020-10-21 09:35 UTC, riimako commented on src/images.tsx
> +export const images: Array<any> = [
Las Gatas Te Mean

2020-10-21 09:35 UTC, merged